# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /
    weight: 10
  - name: Equipo
    url: equipo
    weight: 30
  - name: Organigrama
    url: organigrama
    weight: 35
  - name: Contacto
    url: contacto
    weight: 60
